Epad8 1352 slideshows larger
USEPA/webcms pull request #345
Opened 2021-07-09 16:33 UTC by jbwagner

Have the slides use the medium (640x360px) image instead of the small, update styles accordingly

2021-07-13 14:59 UTC, dcmouyard requested changes
@jbwagner  Great work!

I forgot to specify some details in the ticket: Since we’re changing the gallery responsive image style to 640px, we also want to add larger images so it works on high DPI devices.

We’ll want to create new Large Gallery (960x540) and Huge Gallery (1280x720) image styles and reference them in the responsive image style.

Also, could you investigate why we have nested figures in the markup of the gallery images? I think is a regression from when we first implemented the slideshow gallery component.

```
<figure class="figure figure--gallery">
  <div class="figure__media">
    <div class="contextual"></div>
    <figure class="figure figure--gallery"> // Can we remove this?
      <div class="figure__media"> // Can we remove this?
        <a>
          <img>
        </a>
      </div> // Can we remove this?
    </figure> // Can we remove this?
  </div>
  <figcaption class="figure__caption"></figcaption>
</figure>
```

2021-07-13 14:59 UTC, dcmouyard commented on services/drupal/config/sync/responsive_image.styles.responsive_gallery_image.yml
>          - gallery_small
Here’s where we’ll add `gallery_large` and `gallery_huge`.

2021-07-13 17:46 UTC, jbwagner commented
@dcmouyard Should be all set. The double <figure> was some odd templating, and it might have been renamed at some point. I left what was there but just added a stripped down media template for gallery images. Should only apply for this use case anyway so should be good.

Also just created and added the new image styles for the larger media. Matched those to the ones that already existed, so should slot in nicely. Tested this out on my local with test content.

2021-07-19 20:38 UTC, dcmouyard approved these changes

2021-07-19 20:38 UTC, merged