add documentation
USEPA/webcms pull request #91
Opened 2020-10-22 13:21 UTC by caedstrom

added link to our box standard documentation

2020-10-26 13:14 UTC, cherrypj requested changes
Fix the typo @caedstrom

2020-11-10 18:59 UTC, dcmouyard approved these changes
I pointed two things to keep in mind for future PRs. I’ve fixed these issues in my latest commit.

2020-11-10 18:59 UTC, dcmouyard commented on services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box.twig
> +      <p><strong>Related link</strong>: <a href=”https://www.epa.gov/web-policies-and-procedures/web-standard-boxes”>Web Standard: Boxes</a></p>
Be careful with `”` and `”` characters: they should be `"` here in the code.

2020-11-10 18:59 UTC, dcmouyard commented on services/drupal/web/themes/epa_theme/source/_patterns/05-components/box/box.twig
> +{% if is_demo %}
Moving forward, the `is_demo` variable should be replaced with the `show_documentation` variable when wrapping documentation.

2020-11-10 19:06 UTC, merged